from app.agent.agent_tools import generate_bp_pdf

data = {
  "business_name": { "business_name": "猫乐砂", "company_logo": "https://oaidalleapiprodscus.blob.core.windows.net/private/org-lgMa9Hesim4sDUuVPr7qUy2r/user-k0UqrKJE3N04W86gadM1T05K/img-u0V5kFAwYZ739yDOxFvPUmDq.png?st=2023-12-08T06%3A43%3A09Z&se=2023-12-08T08%3A43%3A09Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2023-12-07T16%3A35%3A41Z&ske=2023-12-08T16%3A35%3A41Z&sks=b&skv=2021-08-06&sig=T0si40lvVjROK9/UWJ4sg3xJnakD0iJ4cpSNF8QAGrA%3D", "phone_number": "你的电话号码", "date": { "year": "2023", "month": "12", "day": "8" }, "responsible_person": "你的名字", "excutive_summary": { "company_objective": "提供高品质的猫砂产品，满足中国市场的需求。", "products_and_services": "我们的主要产品是猫砂，具有吸水性强、无尘、环保等特点。", "target_market": "中国的猫主人和宠物店。", "competitive_analysis": "我们的竞争对手主要是其他猫砂品牌，但我们的产品具有更好的性能和更合理的价格。", "marketing_plan": "我们将通过社交媒体、线上广告和宠物展会等方式进行推广。", "sales_plan": "我们计划通过电商平台和实体店销售我们的产品。", "forecast": "我们预计在第一年能达到100万的销售额。", "financing": "我们正在寻求投资者的投资，以帮助我们扩大生产和销售。", "budget_allocation": "我们的预算将主要用于产品开发、营销和销售。", "staffing_and_hiring": "我们计划招聘销售和营销人员，以推动我们的业务发展。", "location": "我们的办公地点在中国。", "technology": "我们将使用最新的生产技术，以确保产品的质量。", "key_performance_indicators": "我们的主要绩效指标包括销售额、客户满意度和市场份额。" }, "company": { "company_description": "猫乐砂是一家专注于猫砂生产和销售的公司。", "company_overview": "我们的目标是成为中国市场上最受欢迎的猫砂品牌。", "company_mission_statement": "我们的使命是提供最好的猫砂产品，让猫主人和他们的猫都能享受到最好的体验。", "company_philosophy_and_vision_statement": "我们的理念是以客户为中心，我们的愿景是成为中国最大的猫砂供应商。" }, "products_and_services": { "products_and_services_explain": "我们的猫砂是由天然材料制成，具有强大的吸水性和无尘的特点。", "products_and_services_problem": "我们的产品解决了市场上许多猫砂尘埃大、不易清理的问题。", "products_and_services_pricing": "我们的产品定价在市场平均水平，以吸引更多的客户。" }, "marketing_plan": { "market_research": { "primary_market_research": "我们通过调查和访谈了解到，中国的猫主人对猫砂的需求很大，但市场上的产品往往不能满足他们的需求。", "secondary_market_research": "根据市场报告，中国的猫砂市场正在快速增长，预计未来几年将继续保持增长。" }, "target_customer": { "customer_profile": { "customer_age": "20-50岁", "customer_gender": "不限", "customer_location": "中国", "customer_income": "中等收入以上", "customer_occupation": "不限", "customer_education_level": "不限", "customer_interests": "养猫", "customer_habits": "经常在线上购物" }, "business_profile": { "business_industry": "宠物用品", "business_location": "中国", "business_size": "不限", "business_stage": "不限", "business_annual_sales": "不限", "business_challenges": "找到高品质的猫砂供应商" } } }, "company_management": { "company_management_system": "我们的公司管理系统是以目标为导向，注重团队合作。", "company_management_mechanisms": "我们的管理机制包括定期的业务评估和员工培训。" }, "financing_plan": { "financing_amount_and_purpose": "我们正在寻求100万的投资，用于扩大生产和销售。", "financing_price": "我们的融资价格是每股10元。", "financing_investment_return": "我们预计在3年内能实现投资回报。", "financing_rights_and_interests_of_investors": "投资者将获得我们公司的股份和分红权。" }, "risks_and_responses": { "risks_and_responses_risks": "我们面临的风险包括市场竞争、原材料价格波动等。", "risks_and_responses_responses": "我们将通过提供高品质的产品、优化生产流程和建立稳定的供应链来应对这些风险。" } },
  "company_logo": "https://oaidalleapiprodscus.blob.core.windows.net/private/org-lgMa9Hesim4sDUuVPr7qUy2r/user-k0UqrKJE3N04W86gadM1T05K/img-LfG8pUWQY4TuUhkHKZCDxMzw.png?st=2023-12-08T10%3A17%3A24Z&se=2023-12-08T12%3A17%3A24Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2023-12-07T16%3A37%3A09Z&ske=2023-12-08T16%3A37%3A09Z&sks=b&skv=2021-08-06&sig=OoEYhD6Eqkv90S8o7z8JpLEOxe5Y%2BOkKr1nEvIe5EEo%3D",
  "phone_number": "13067826615",
  "date": {
    "year": "2023",
    "month": "12",
    "day": "08"
  },
  "responsible_person": "惠凯",
  "excutive_summary": {
    "company_objective": "为年轻人提供高质量的滑板产品和服务",
    "products_and_services": "我们提供各种类型的滑板，包括初学者滑板，专业滑板，以及定制滑板",
    "target_market": "我们的目标市场是年轻人，特别是那些对滑板有热情的人",
    "competitive_analysis": "我们的竞争对手主要是其他滑板品牌，但我们的产品和服务的质量和多样性使我们在市场上具有竞争优势",
    "marketing_plan": "我们计划通过社交媒体和滑板活动进行营销",
    "sales_plan": "我们计划通过我们的网站和合作的零售商销售我们的产品",
    "forecast": "我们预计在未来一年内，我们的销售额将增长20%",
    "financing": "我们目前正在寻找投资者，以帮助我们扩大生产和销售",
    "budget_allocation": "我们的预算主要分配给产品开发，营销，和销售",
    "staffing_and_hiring": "我们计划招聘更多的员工，以支持我们的业务扩张",
    "location": "我们的公司位于中国",
    "technology": "我们使用最新的技术来制造我们的滑板，以确保它们的质量和耐用性",
    "key_performance_indicators": "我们的关键绩效指标包括销售额，客户满意度，和市场份额"
  }
}

#print(generate_bp_pdf({'business_name': '猫乐砂', 'company_logo': 'https://oaidalleapiprodscus.blob.core.windows.net/private/org-lgMa9Hesim4sDUuVPr7qUy2r/user-k0UqrKJE3N04W86gadM1T05K/img-u0V5kFAwYZ739yDOxFvPUmDq.png?st=2023-12-08T06%3A43%3A09Z&se=2023-12-08T08%3A43%3A09Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2023-12-07T16%3A35%3A41Z&ske=2023-12-08T16%3A35%3A41Z&sks=b&skv=2021-08-06&sig=T0si40lvVjROK9/UWJ4sg3xJnakD0iJ4cpSNF8QAGrA%3D', 'phone_number': '你的电话号码', 'date': {'year': '2023', 'month': '12', 'day': '8'}, 'responsible_person': '你的名字', 'excutive_summary': {'company_objective': '提供高品质的猫砂产品，满足中国市场的需求。', 'products_and_services': '我们的主要产品是猫砂，具有吸水性强、无尘、环保等特点。', 'target_market': '中国的猫主人和宠物店。', 'competitive_analysis': '我们的竞争对手主要是其他猫砂品牌，但我们的产品具有更好的性能和更合理的价格。', 'marketing_plan': '我们将通过社交媒体、线上广告和宠物展会等方式进行推广。', 'sales_plan': '我们计划通过电商平台和实体店销售我们的产品。', 'forecast': '我们预计在第一年能达到100万的销售额。', 'financing': '我们正在寻求投资者的投资，以帮助我们扩大生产和销售。', 'budget_allocation': '我们的预算将主要用于产品开发、营销和销售。', 'staffing_and_hiring': '我们计划招聘销售和营销人员，以推动我们的业务发展。', 'location': '我们的办公地点在中国。', 'technology': '我们将使用最新的生产技术，以确保产品的质量。', 'key_performance_indicators': '我们的主要绩效指标包括销售额、客户满意度和市场份额。'}, 'company': {'company_description': '猫乐砂是一家专注于猫砂生产和销售的公司。', 'company_overview': '我们的目标是成为中国市场上最受欢迎的猫砂品牌。', 'company_mission_statement': '我们的使命是提供最好的猫砂产品，让猫主人和他们的猫都能享受到最好的体验。', 'company_philosophy_and_vision_statement': '我们的理念是以客户为中心，我们的愿景是成为中国最大的猫砂供应商。'}, 'products_and_services': {'products_and_services_explain': '我们的猫砂是由天然材料制成，具有强大的吸水性和无尘的特点。', 'products_and_services_problem': '我们的产品解决了市场上许多猫砂尘埃大、不易清理的问题。', 'products_and_services_pricing': '我们的产品定价在市场平均水平，以吸引更多的客户。'}, 'marketing_plan': {'market_research': {'primary_market_research': '我们通过调查和访谈了解到，中国的猫主人对猫砂的需求很大，但市场上的产品往往不能满足他们的需求。', 'secondary_market_research': '根据市场报告，中国的猫砂市场正在快速增长，预计未来几年将继续保持增长。'}, 'target_customer': {'customer_profile': {'customer_age': '20-50岁', 'customer_gender': '不限', 'customer_location': '中国', 'customer_income': '中等收入以上', 'customer_occupation': '不限', 'customer_education_level': '不限', 'customer_interests': '养猫', 'customer_habits': '经常在线上购物'}, 'business_profile': {'business_industry': '宠物用品', 'business_location': '中国', 'business_size': '不限', 'business_stage': '不限', 'business_annual_sales': '不限', 'business_challenges': '找到高品质的猫砂供应商'}}}, 'company_management': {'company_management_system': '我们的公司管理系统是以目标为导向，注重团队合作。', 'company_management_mechanisms': '我们的管理机制包括定期的业务评估和员工培训。'}, 'financing_plan': {'financing_amount_and_purpose': '我们正在寻求100万的投资，用于扩大生产和销售。', 'financing_price': '我们的融资价格是每股10元。', 'financing_investment_return': '我们预计在3年内能实现投资回报。', 'financing_rights_and_interests_of_investors': '投资者将获得我们公司的股份和分红权。'}, 'risks_and_responses': {'risks_and_responses_risks': '我们面临的风险包括市场竞争、原材料价格波动等。', 'risks_and_responses_responses': '我们将通过提供高品质的产品、优化生产流程和建立稳定的供应链来应对这些风险。'}}))

print(generate_bp_pdf(data))